import { pianoImg, theoryImg } from '../../assets/images'

export const blogArticles = [
  {
    id: 1,
    slug: '5-essential-finger-dexterity-drills-every-keyboard-player-must-practice-daily',
    category: 'Piano Technique',
    title: '5 Essential Finger Dexterity Drills Every Keyboard Player Must Practice Daily',
    excerpt: 'Hanon and Czerny exercises broken down for modern keyboard players. How 15 minutes of intentional slow practice builds velocity, clean articulation, and prevents wrist fatigue.',
    date: 'Sep 12, 2026',
    readTime: '5 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Piano',
    image: pianoImg,
    accent: 'from-purple-600 to-indigo-700',
    intro: 'Whether you are sitting down at a keyboard for the very first time or looking to break through a technical plateau, hand mechanics and finger independence determine your speed, control, and musical expression. At PraiseWave, we teach students that clean playing is not about brute strength — it is about efficiency of motion and relaxed wrist alignment.',
    sections: [
      {
        heading: '1. The 5-Finger Independent Lift Drill (Five-Finger Pattern)',
        body: 'Place your right hand in the C Major 5-finger position (C-D-E-F-G). While holding all five keys down gently, lift only the thumb (1) and strike C cleanly with a firm fingertip. Repeat four times in steady quarter notes. Next, repeat with the index finger (2), middle finger (3), ring finger (4), and pinky (5). Focus on keeping the unused fingers rested on key tops without tension.',
        tip: 'The 4th finger (ring finger) naturally shares a tendon with the 3rd and 5th fingers. Never force it high; focus on independent activation rather than exaggerated lift height.',
      },
      {
        heading: '2. The Hanon No. 1 Expansion with Metronome Discipline',
        body: 'Hanon Exercise No. 1 is designed to train the 4th and 5th fingers of both hands while expanding the stretch between the 1st and 2nd fingers. Start at a slow tempo of 60 BPM (one note per click). Ensure every single note has identical volume and duration (legato touch). Only increase tempo by 4 BPM once your hands can play two full octaves ascending and descending with zero tension.',
        tip: 'Practice in contrary motion (hands moving away from each other) to build equal coordination in both the dominant and non-dominant hand.',
      },
      {
        heading: '3. Thumb-Under Arpeggio Pivoting (1-2-3-1 Crossing)',
        body: 'Smooth scalar runs and arpeggios require the thumb to smoothly glide underneath the palm without lifting your wrist into the air. Practice passing your thumb under fingers 2 and 3 on C Major, G Major, and F Major scales. Keep your wrist level with the keyboard bed — imagine balancing a coin on the back of your hand.',
      },
      {
        heading: '4. Staccato vs. Legato Articulation Workout',
        body: 'Play the ascending scale in the right hand with a crisp, bouncy staccato (plucking motion from the fingertip) while the left hand plays smooth, connected legato whole notes. Switch hands on the way down. This trains your brain to send distinct motor commands to each hand independently.',
      },
      {
        heading: '5. Dynamic Finger Weight Control (Pianissimo to Fortissimo)',
        body: 'Play a repetitive 5-finger pattern where each repetition changes dynamics: Pianissimo (pp) -> Mezzo-Forte (mf) -> Fortissimo (ff) -> Diminuendo back to Pianissimo. Control the volume purely through arm weight drop and finger speed, keeping your shoulders relaxed and breathing steady.',
      },
    ],
    keyTakeaways: [
      '15 minutes of slow, mindful daily practice beats 2 hours of rushed, sloppy playing.',
      'Always keep wrists neutral and level with the white keys to prevent repetitive strain.',
      'Use a metronome at 60–70 BPM before trying to play at high performance tempos.',
      'Finger 4 independence takes consistent patience — never force or strain.',
    ],
  },
  {
    id: 2,
    slug: 'understanding-chord-progressions-how-to-play-any-gospel-song-by-ear',
    category: 'Chord Progressions',
    title: 'Understanding Chord Progressions: How to Play Any Gospel Song by Ear',
    excerpt: 'The 1-4-5-6 progression explained for keyboard players. Once you understand how chords relate to each other, you can play and improvise over any worship song with confidence.',
    date: 'Sep 06, 2026',
    readTime: '6 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Chords',
    image: theoryImg,
    accent: 'from-cyan-600 to-blue-700',
    intro: 'Have you ever wondered how seasoned church keyboardists can sit down and play along with songs they have never formally rehearsed? The secret is not memorizing thousands of individual songs — it is understanding the Nashville Number System and diatonic chord relationships in Western harmony.',
    sections: [
      {
        heading: '1. What Are Diatonic Chords in a Major Key?',
        body: 'Every major scale contains 7 unique notes, and building triads on each scale degree creates a fixed series of Major, Minor, and Diminished chords that never change:',
        chart: [
          { number: 'I (One)', chord: 'Major (C)', role: 'Home / Tonic - Resolves all musical tension' },
          { number: 'ii (Two)', chord: 'Minor (Dm)', role: 'Pre-dominant / Smooth transitional movement' },
          { number: 'iii (Three)', chord: 'Minor (Em)', role: 'Gentle tonic substitute / Reflective color' },
          { number: 'IV (Four)', chord: 'Major (F)', role: 'Subdominant / Lifting, expansive worship emotion' },
          { number: 'V (Five)', chord: 'Major (G)', role: 'Dominant / Creates powerful pull back to I' },
          { number: 'vi (Six)', chord: 'Minor (Am)', role: 'Relative minor / Emotional, introspective atmosphere' },
          { number: 'vii° (Seven)', chord: 'Diminished (Bdim)', role: 'Leading tone tension / Passing chord' },
        ],
      },
      {
        heading: '2. The Iconic Gospel Worship Formula: I - V - vi - IV',
        body: 'Over 80% of modern worship anthems and gospel ballads are built on variations of this 4-chord sequence. In the key of C Major, this is: C -> G -> Am -> F. In the key of G Major: G -> D -> Em -> C. In the key of D Major: D -> A -> Bm -> G.',
        tip: 'Learn this progression across 3 primary gospel keys (C, G, D, and F). Once your hands know the number shapes, transposing on the fly becomes effortless.',
      },
      {
        heading: '3. Chord Inversions: Eliminate Awkward Hand Jumps',
        body: 'Beginners frequently jump their entire hand up and down the keyboard in root positions (C root -> G root -> Am root -> F root). This sounds choppy and disconnected. By using chord inversions (Root, 1st Inversion, 2nd Inversion), your fingers move by only 1 or 2 keys, creating a lush, professional gospel keyboard pad.',
      },
      {
        heading: '4. The 2-5-1 and Passing Chords in Gospel Harmony',
        body: 'To add soulful richness between main sections, gospel players insert secondary dominants and 2-5-1 cadences. For example, before resolving to the IV chord (F Major), you can insert a secondary dominant C7 (or Gm7 -> C7 -> Fmaj9). This creates the warm gospel swell heard in live services.',
      },
    ],
    keyTakeaways: [
      'Think in numbers (I, IV, V, vi) rather than isolated chord names.',
      'Use chord inversions to keep hand movements compact and smooth.',
      'Master the I - V - vi - IV progression in keys C, G, D, and F first.',
      'Add suspended 2nds and 9ths (e.g. Cadd9, Fsus2) for modern worship texture.',
    ],
  },
  {
    id: 3,
    slug: 'the-circle-of-fifths-demystified-how-to-transpose-and-modulate-any-song',
    category: 'Music Theory',
    title: 'The Circle of Fifths Demystified: How to Transpose and Modulate Any Song',
    excerpt: 'Stop memorizing key signatures by rote. Understand the geometric symmetry of Western harmony and start composing your own chord progressions with confidence.',
    date: 'Aug 29, 2026',
    readTime: '4 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Theory',
    image: theoryImg,
    accent: 'from-emerald-600 to-teal-700',
    intro: 'The Circle of Fifths is often taught as an intimidating academic diagram, but in practice, it is the ultimate musician’s compass. Once you understand how each key connects to its neighbours, key transposition, modulation, and reading sheet music become second nature.',
    sections: [
      {
        heading: '1. The Clockface Layout of Keys',
        body: 'Imagine a clock. At 12 o’clock sits C Major (0 sharps, 0 flats). Moving clockwise by intervals of a perfect fifth (7 semitones), each step adds exactly one sharp (#): 1 o’clock = G (1#), 2 o’clock = D (2#), 3 o’clock = A (3#), 4 o’clock = E (4#), 5 o’clock = B (5#), 6 o’clock = F# (6#). Moving counter-clockwise by fourths adds flats (b): 11 o’clock = F (1b), 10 o’clock = Bb (2b), 9 o’clock = Eb (3b).',
      },
      {
        heading: '2. Instantly Finding Closely Related Keys',
        body: 'Any key on the circle is intimately related to its immediate neighbors to the left and right, plus their corresponding inner relative minors. For C Major, its harmonic family is F Major (left), G Major (right), A minor (relative), D minor (ii), and E minor (iii). These 6 keys share nearly identical notes, making seamless chord borrowing natural.',
      },
      {
        heading: '3. Modulation Techniques for Live Worship',
        body: 'When leading a congregation or band into a dramatic key change on the final chorus, you can modulate up a whole step (e.g., C Major to D Major) by using the V of the new key (A Major or A7) as a pivot chord. The Circle of Fifths shows you the exact bridge chord needed to make the transition sound intentional and uplifting.',
      },
    ],
    keyTakeaways: [
      'Clockwise adds sharps (# by 5ths); Counter-clockwise adds flats (b by 4ths).',
      'The inner circle contains the relative minor of every major key (e.g., C Maj -> A min).',
      'Neighboring keys on the circle provide smooth harmonic modulation paths.',
    ],
  },
  {
    id: 4,
    slug: 'how-to-build-rock-solid-rhythm-as-a-keyboard-player-using-a-metronome',
    category: 'Rhythm & Timing',
    title: 'How to Build Rock-Solid Rhythm as a Keyboard Player Using a Metronome',
    excerpt: 'Most beginners skip metronome practice — and it shows. Learn the exact progressive method our instructors use to help students lock into a groove and never rush or drag.',
    date: 'Aug 21, 2026',
    readTime: '7 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Rhythm',
    image: pianoImg,
    accent: 'from-amber-600 to-rose-700',
    intro: 'Rhythm is the heartbeat of all music. You can play the most intricate chords in the world, but if your timing rushes during easy passages or drags during difficult transitions, the performance loses its soul. Here is how we develop internal clock precision at PraiseWave.',
    sections: [
      {
        heading: '1. The Disappearing Metronome Technique',
        body: 'When your rhythm is perfectly locked in with the metronome, your brain experiences an optical-audio illusion: the click seems to "disappear" beneath your piano strike. If you hear the click distinctly before or after your note, you are rushing or lagging. Practice single-finger strikes on beat until the click vanishes.',
      },
      {
        heading: '2. Subdividing 8ths and 16ths in Your Head',
        body: 'Never count just 1 - 2 - 3 - 4. Always internalize the subdivisions: "1 - and - 2 - and - 3 - and - 4 - and" for 8th note worship grooves, and "1 - e - and - a, 2 - e - and - a" for fast gospel shuffles. This prevents the tendency to speed up during open chords.',
      },
      {
        heading: '3. Practicing with the Metronome on Beats 2 and 4 Only',
        body: 'In modern pop, gospel, and contemporary worship music, the snare drum hits on beats 2 and 4 (the backbeat). Set your metronome to click only on beats 2 and 4 instead of all four beats. You must supply beats 1 and 3 internally. This single exercise will instantly transform you from a robotic player into a groove-locked musician.',
      },
    ],
    keyTakeaways: [
      'Aim for the "vanishing click" phenomenon where your strike masks the metronome tick.',
      'Always count internal subdivisions out loud during slow practice.',
      'Practice with backbeat clicks (beats 2 & 4) to master contemporary gospel feel.',
    ],
  },
  {
    id: 5,
    slug: 'left-hand-independence-the-missing-skill-that-separates-good-from-great-keyboard-players',
    category: 'Hand Technique',
    title: 'Left Hand Independence: The Missing Skill That Separates Good from Great Keyboard Players',
    excerpt: 'Many students can play with their right hand but struggle with coordinating the left. Here is our structured system for developing true two-hand independence on the keyboard.',
    date: 'Aug 14, 2026',
    readTime: '6 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Technique',
    image: pianoImg,
    accent: 'from-pink-600 to-fuchsia-700',
    intro: 'The dreaded "left hand freeze" is the most common roadblock faced by self-taught keyboard players. When the right hand starts playing a melody or fast arpeggio, the left hand involuntarily mirrors the movement or stumbles. Breaking this requires isolating rhythmic and harmonic roles.',
    sections: [
      {
        heading: '1. Isolate and Master the Left Hand Role First',
        body: 'Never try to learn both hands simultaneously from scratch on a new piece. Play the left hand part alone until you can play it effortlessly while carrying on a conversation or looking away from the keys. If the left hand requires conscious CPU power from your brain, it will derail when the right hand enters.',
      },
      {
        heading: '2. Octave-Fifth Root Foundations (1 - 5 - 8 Shapes)',
        body: 'In worship keyboard playing, the left hand rarely plays full dense triads in the low register, which creates muddy sound. Instead, master the open 1-5-8 shell voicing (e.g. C1 - G1 - C2). This provides powerful, clean bass support without cluttering the vocal or guitar frequencies.',
      },
      {
        heading: '3. Polyrhythmic Tapping Drills Away from the Piano',
        body: 'Sit at a desk. Tap steady quarter notes with your left hand (1, 2, 3, 4) while tapping eighth notes with your right hand (1-and, 2-and, 3-and, 4-and). Once comfortable, reverse hands. Next, try 3 against 2 polyrhythms. Training your motor cortex away from the keys accelerates keyboard coordination tenfold.',
      },
    ],
    keyTakeaways: [
      'Learn the left hand accompaniment until it is 100% automated before combining hands.',
      'Use 1-5-8 open voicings in the bass register to keep tone crisp and non-muddy.',
      'Practice tabletop hand tapping drills daily for 5 minutes.',
    ],
  },
  {
    id: 6,
    slug: 'church-keyboard-playing-101-how-to-support-a-worship-team-as-a-beginner',
    category: 'Worship Keyboard',
    title: 'Church Keyboard Playing 101: How to Support a Worship Team as a Beginner',
    excerpt: 'Playing keyboard in a church context requires more than just knowing chords. Learn how to listen, respond, and support a worship team with tasteful, ministry-focused playing.',
    date: 'Aug 04, 2026',
    readTime: '5 min read',
    author: 'Calix Joshua',
    authorRole: 'Founder & Lead Mentor, PraiseWave',
    tag: 'Worship',
    image: theoryImg,
    accent: 'from-yellow-600 to-amber-700',
    intro: 'Playing keyboard in a live church or worship team setting is a unique discipline. Unlike solo piano performances where you fill every sonic space, band keyboard playing is all about space, frequency awareness, and supporting the congregation’s focus.',
    sections: [
      {
        heading: '1. Tone Layering: Piano + Ambient Pad Magic',
        body: 'The signature sound of modern praise and worship is a warm grand piano layered with a subtle, lush analog or string pad with high cut. The pad fills the background space between phrases, allowing you to play sparse, tasteful piano chords without awkward silence.',
      },
      {
        heading: '2. Stay Out of the Bass Player’s Frequency Lane',
        body: 'The number one mistake beginner church pianists make is pounding heavy low octaves with their left hand. If your church has a bass guitarist, stay in the mid-register (C3 to C5) with simple inversions and light root taps. Let the bassist handle the low rumble.',
      },
      {
        heading: '3. The Power of Space & Dynamic Arcs',
        body: 'During intimate prayer or vocal-led verses, drop down to single, sustained whole-note chords (Pad/Piano swell). Build into rhythmic eighth-note broken chords during the chorus, and unleash full octave voicings only on the explosive climax. Dynamics tell the emotional story.',
      },
    ],
    keyTakeaways: [
      'Layer a warm ambient pad with piano to create smooth atmospheric transitions.',
      'Leave the sub-bass frequencies for the bass guitarist — play upper-register voicings.',
      'Serve the room and congregation — less is often vastly more powerful.',
    ],
  },
]
